# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boil < Formula
  desc ""
  homepage "https://github.com/santiagomed/boil"
  version "0.3.1-beta"

  on_macos do
    on_intel do
      url "https://github.com/santiagomed/boil/releases/download/v0.3.1-beta/boil_Darwin_x86_64.tar.gz"
      sha256 "604cb9bde396385934153643b73fc53d68e1d34676bba5deb0bedabd1fdd4331"

      def install
        bin.install "boil"
      end
    end
    on_arm do
      url "https://github.com/santiagomed/boil/releases/download/v0.3.1-beta/boil_Darwin_arm64.tar.gz"
      sha256 "2d736e4fae2fa41ea031be9768dd48fefb36902e2923f78ab6687c3f6960c2df"

      def install
        bin.install "boil"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/santiagomed/boil/releases/download/v0.3.1-beta/boil_Linux_x86_64.tar.gz"
        sha256 "ad80bcbdb9acaf26e1b31df90b2a67f0c126bdad02a3707cf849b0de93d9f2c1"

        def install
          bin.install "boil"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/santiagomed/boil/releases/download/v0.3.1-beta/boil_Linux_arm64.tar.gz"
        sha256 "26cf14cc179d1f7fb0c7b374d9a2a3422f28a149602a35465041ab5f706f6691"

        def install
          bin.install "boil"
        end
      end
    end
  end

  test do
    system "#{bin}/boil --version"
  end
end
