# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boil < Formula
  desc ""
  homepage "https://github.com/santiagomed/boil"
  version "0.3.0-beta"

  on_macos do
    on_intel do
      url "https://github.com/santiagomed/boil/releases/download/v0.3.0-beta/boil_Darwin_x86_64.tar.gz"
      sha256 "08e3b2f2f5b5d1bad4cb97914b4b2570cd1f5c8bc79992bc02330d1097c7b70f"

      def install
        bin.install "boil"
      end
    end
    on_arm do
      url "https://github.com/santiagomed/boil/releases/download/v0.3.0-beta/boil_Darwin_arm64.tar.gz"
      sha256 "9c41dd9baf8281bc9e4f807ec4bf4893ade68d3761dd1483fd6eb262000a7ef1"

      def install
        bin.install "boil"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/santiagomed/boil/releases/download/v0.3.0-beta/boil_Linux_x86_64.tar.gz"
        sha256 "6d2667d6a9d9a5e690d64f449479b6c667a73e4b846604ce512aa106e2c8a605"

        def install
          bin.install "boil"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/santiagomed/boil/releases/download/v0.3.0-beta/boil_Linux_arm64.tar.gz"
        sha256 "1ceb3b5475583f92bf297f9398ecdc39b3d21702aaa0fb8a17c55a5167d328bc"

        def install
          bin.install "boil"
        end
      end
    end
  end

  test do
    system "#{bin}/boil --version"
  end
end
