# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boil < Formula
  desc ""
  homepage "https://github.com/santiagomed/boil"
  version "0.2.0-beta"

  on_macos do
    on_intel do
      url "https://github.com/santiagomed/boil/releases/download/v0.2.0-beta/boil_Darwin_x86_64.tar.gz"
      sha256 "7f32e860fb8a28e0cc8fa9c34e22bfc4635ee2b8198801c1f8e631020ee56b3b"

      def install
        bin.install "boil"
      end
    end
    on_arm do
      url "https://github.com/santiagomed/boil/releases/download/v0.2.0-beta/boil_Darwin_arm64.tar.gz"
      sha256 "4d7a517f17f534ecf7d462ae10557ebee0b530f8d5bb9ac42ed8339b1ccd3597"

      def install
        bin.install "boil"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/santiagomed/boil/releases/download/v0.2.0-beta/boil_Linux_x86_64.tar.gz"
        sha256 "6ed3a1ad0c8fc8738bfbd129ffd8f895f021545912647d33a130b4694e35f035"

        def install
          bin.install "boil"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/santiagomed/boil/releases/download/v0.2.0-beta/boil_Linux_arm64.tar.gz"
        sha256 "388070df69ca1543684c460f56bfa46750df75c75f426e1adb33393c086bd088"

        def install
          bin.install "boil"
        end
      end
    end
  end

  test do
    system "#{bin}/boil --version"
  end
end
